### ISSUE TITLE
Not downloading anymore

### ISSUE THREAD

**Issue by ellite** [hugomfandrade/RTPPlay-Video-Downloader-Chrome-Extension#8]
Hi. The extension stopped working. Download is stuck at 0%.

**Comment by hugomfandrade** [comment]
Hi. I will look to correct this issue, but I will be unable to do it sooner than Friday

**Comment by ellite** [comment]
Thanks. Thank you for the great work.

**Comment by jpsapara** [comment]
Olá! Antes de mais quero dar-te os parabéns por esta excelente extensão!
Todavia, recentemente a mesma deixou de funcionar e já não está disponível na WebStore. Vai haver alguma forma de resolver este problema?
Continua o bom trabalho!

**Comment by hugomfandrade** [comment]
A new version is available here / Uma nova versão está disponível neste link
https://github.com/hugomfandrade/apk-releases/raw/master/rtp-play-downloader-chrome-extension/RTPPlayer-Downloader-v1.2.2.zip

The extension is no longer available in the WebStore. You should unzip it and follow the instructions on the README page
A extensão já não está disponível na WebStore. Deverá extrair a pasta do ficheiro zip e seguir as instruções na página README
